import SwiftUI

@MainActor
enum PageRegistry {
    static func view(for leaf: Leaf) -> AnyView {
        switch leaf.pageBuilder {
        case .placeholder:
            return AnyView(PlaceholderPage(leaf: leaf))
        case .real(let symbol):
            if let builder = realPages[symbol] {
                return builder(leaf)
            }
            return AnyView(PlaceholderPage(leaf: leaf))
        }
    }

    private static let realPages: [String: (Leaf) -> AnyView] = [
        "Adding a search interface to your app":                                                    { _ in AnyView(AddingSearchInterfacePage()) },
        "AlternatingRowBackgroundBehavior":                                                         { _ in AnyView(AlternatingRowBackgroundBehaviorTypePage()) },
        "AnyTabContent":                                                                            { _ in AnyView(AnyTabContentPage()) },
        "Applying Liquid Glass to custom views":                                                    { _ in AnyView(ApplyingLiquidGlassPage()) },
        "AutomaticGlassBackgroundEffect":                                                           { _ in AnyView(AutomaticGlassBackgroundEffectPage()) },
        "BackgroundProminence":                                                                     { _ in AnyView(BackgroundProminenceTypePage()) },
        "BadgeProminence":                                                                          { _ in AnyView(BadgeProminencePage()) },
        "BreakthroughEffect":                                                                       { _ in AnyView(BreakthroughEffectPage()) },
        "Bringing multiple windows to your SwiftUI app":                                            { _ in AnyView(BringingMultipleWindowsToYourSwiftUIAppPage()) },
        "Bringing robust navigation structure to your SwiftUI app":                                 { _ in AnyView(BringingRobustNavigationStructurePage()) },
        "ButtonStyle":                                                                              { _ in AnyView(ButtonStyleProtocolPage()) },
        "ButtonStyleConfiguration":                                                                 { _ in AnyView(ButtonStyleConfigurationPage()) },
        "ColorScheme":                                                                              { _ in AnyView(ColorSchemeTypePage()) },
        "ColorSchemeContrast":                                                                      { _ in AnyView(ColorSchemeContrastTypePage()) },
        "Configuring views":                                                                        { _ in AnyView(ConfiguringViewsPage()) },
        "ControlActiveState":                                                                       { _ in AnyView(ControlActiveStatePage()) },
        "ControlGroupStyle":                                                                        { _ in AnyView(ControlGroupStylePage()) },
        "ControlGroupStyleConfiguration":                                                           { _ in AnyView(ControlGroupStylePage()) },
        "Customizing window styles and state-restoration behavior in macOS":                        { _ in AnyView(CustomizingWindowStylesAndStateRestorationBehaviorInMacOSPage()) },
        "DatePickerStyle":                                                                          { _ in AnyView(DatePickerStylePage()) },
        "Declaring a custom view":                                                                  { _ in AnyView(DeclaringCustomViewPage()) },
        "DefaultGlassEffectShape":                                                                  { _ in AnyView(DefaultGlassEffectShapePage()) },
        "DisclosureGroup":                                                                          { _ in AnyView(DisclosureGroupPage()) },
        "DisclosureGroupStyle":                                                                     { _ in AnyView(DisclosureGroupStylePage()) },
        "DismissAction":                                                                            { _ in AnyView(DismissPage()) },
        "DismissBehavior":                                                                          { _ in AnyView(DismissPage()) },
        "DismissWindowAction":                                                                      { _ in AnyView(DismissWindowPage()) },
        "DisplayProxy":                                                                             { _ in AnyView(DisplayProxyPage()) },
        "Displaying data in lists":                                                                 { _ in AnyView(DisplayingDataInListsPage()) },
        "EditActions":                                                                              { _ in AnyView(EditActionsTypePage()) },
        "EditMode":                                                                                 { _ in AnyView(EditModeTypePage()) },
        "EditableCollectionContent":                                                                { _ in AnyView(EditableCollectionContentTypePage()) },
        "EmptyModifier":                                                                            { _ in AnyView(EmptyModifierPage()) },
        "Enhancing your app content with tab navigation":                                           { _ in AnyView(EnhancingTabNavigationPage()) },
        "EnvironmentValues/colorScheme":                                                            { _ in AnyView(ColorSchemeEnvironmentPage()) },
        "EnvironmentValues/colorSchemeContrast":                                                    { _ in AnyView(ColorSchemeContrastEnvironmentPage()) },
        "EnvironmentValues/dismiss":                                                                { _ in AnyView(DismissPage()) },
        "EnvironmentValues/dismissWindow":                                                          { _ in AnyView(DismissWindowPage()) },
        "EnvironmentValues/isEnabled":                                                              { _ in AnyView(IsEnabledPage()) },
        "EnvironmentValues/isSceneCaptured":                                                        { _ in AnyView(IsSceneCapturedPage()) },
        "EnvironmentValues/labelsVisibility":                                                       { _ in AnyView(LabelsVisibilityEnvironmentPage()) },
        "EnvironmentValues/openWindow":                                                             { _ in AnyView(OpenWindowPage()) },
        "EnvironmentValues/redactionReasons":                                                       { _ in AnyView(RedactionReasonsEnvironmentPage()) },
        "EnvironmentValues/sidebarRowSize":                                                         { _ in AnyView(SidebarRowSizeEnvironmentPage()) },
        "EnvironmentValues/supportsMultipleWindows":                                                { _ in AnyView(SupportsMultipleWindowsPage()) },
        "EnvironmentalModifier":                                                                    { _ in AnyView(EnvironmentalModifierPage()) },
        "FeatheredGlassBackgroundEffect":                                                           { _ in AnyView(FeatheredGlassBackgroundEffectPage()) },
        "ForEach":                                                                                  { _ in AnyView(ForEachPage()) },
        "FormStyle":                                                                                { _ in AnyView(FormStylePage()) },
        "FormStyleConfiguration":                                                                   { _ in AnyView(FormStylePage()) },
        "GaugeStyle":                                                                               { _ in AnyView(GaugeStylePage()) },
        "GaugeStyleConfiguration":                                                                  { _ in AnyView(GaugeStylePage()) },
        "Glass/interactive(_:)":                                                                    { _ in AnyView(GlassInteractivePage()) },
        "GlassBackgroundDisplayMode":                                                               { _ in AnyView(GlassBackgroundDisplayModePage()) },
        "GlassBackgroundEffect":                                                                    { _ in AnyView(GlassBackgroundEffectProtocolPage()) },
        "GlassBackgroundEffectConfiguration":                                                       { _ in AnyView(GlassBackgroundEffectConfigurationPage()) },
        "GlassButtonStyle":                                                                         { _ in AnyView(GlassButtonStyleTypePage()) },
        "GlassEffectContainer":                                                                     { _ in AnyView(GlassEffectContainerPage()) },
        "GlassEffectTransition":                                                                    { _ in AnyView(GlassEffectTransitionPage()) },
        "GlassProminentButtonStyle":                                                                { _ in AnyView(GlassProminentButtonStyleTypePage()) },
        "GroupBoxStyle":                                                                            { _ in AnyView(GroupBoxStylePage()) },
        "GroupBoxStyleConfiguration":                                                               { _ in AnyView(GroupBoxStylePage()) },
        "HSplitView":                                                                               { _ in AnyView(HSplitViewPage()) },
        "IndexViewStyle":                                                                           { _ in AnyView(IndexViewStylePage()) },
        "IndexedIdentifierCollection":                                                              { _ in AnyView(IndexedIdentifierCollectionTypePage()) },
        "Label":                                                                                    { _ in AnyView(LabelTypePage()) },
        "LabelStyle":                                                                               { _ in AnyView(LabelStylePage()) },
        "LabelStyleConfiguration":                                                                  { _ in AnyView(LabelStylePage()) },
        "LabeledContentStyle":                                                                      { _ in AnyView(LabeledContentStylePage()) },
        "LabeledContentStyleConfiguration":                                                         { _ in AnyView(LabeledContentStylePage()) },
        "Landmarks: Building an app with Liquid Glass":                                             { _ in AnyView(LandmarksLiquidGlassPage()) },
        "List":                                                                                     { _ in AnyView(ListPage()) },
        "ListItemTint":                                                                             { _ in AnyView(ListItemTintPage()) },
        "ListSectionSpacing":                                                                       { _ in AnyView(ListSectionSpacingPage()) },
        "ListStyle":                                                                                { _ in AnyView(ListStyleProtocolPage()) },
        "Managing search interface activation":                                                     { _ in AnyView(ManagingSearchInterfaceActivationPage()) },
        "Manipulable":                                                                              { _ in AnyView(ManipulableProtocolPage()) },
        "ManipulableModifier":                                                                      { _ in AnyView(ManipulableModifierPage()) },
        "ManipulableResponderModifier":                                                             { _ in AnyView(ManipulableResponderModifierPage()) },
        "ManipulableTransformBindingModifier":                                                      { _ in AnyView(ManipulableTransformBindingModifierPage()) },
        "ManipulationGeometryModifier":                                                             { _ in AnyView(ManipulationGeometryModifierPage()) },
        "ManipulationGestureModifier":                                                              { _ in AnyView(ManipulationGestureModifierPage()) },
        "ManipulationUsingGestureStateModifier":                                                    { _ in AnyView(ManipulationUsingGestureStateModifierPage()) },
        "MenuStyle":                                                                                { _ in AnyView(MenuStylePage()) },
        "MenuStyleConfiguration":                                                                   { _ in AnyView(MenuStylePage()) },
        "Migrating to new navigation types":                                                        { _ in AnyView(MigratingToNewNavigationTypesPage()) },
        "ModifiedContent":                                                                          { _ in AnyView(ModifiedContentPage()) },
        "NavigationLink":                                                                           { _ in AnyView(NavigationLinkPage()) },
        "NavigationPath":                                                                           { _ in AnyView(NavigationPathPage()) },
        "NavigationSplitView":                                                                      { _ in AnyView(NavigationSplitViewPage()) },
        "NavigationSplitViewColumn":                                                                { _ in AnyView(NavigationSplitViewColumnPage()) },
        "NavigationSplitViewStyle":                                                                 { _ in AnyView(NavigationSplitViewStylePage()) },
        "NavigationSplitViewVisibility":                                                            { _ in AnyView(NavigationSplitViewVisibilityPage()) },
        "NavigationStack":                                                                          { _ in AnyView(NavigationStackPage()) },
        "NavigationView":                                                                           { _ in AnyView(NavigationViewPage()) },
        "OpenWindowAction":                                                                         { _ in AnyView(OpenWindowPage()) },
        "OutlineGroup":                                                                             { _ in AnyView(OutlineGroupPage()) },
        "Performing a search operation":                                                            { _ in AnyView(PerformingSearchOperationPage()) },
        "PickerStyle":                                                                              { _ in AnyView(PickerStylePage()) },
        "PlateGlassBackgroundEffect":                                                               { _ in AnyView(PlateGlassBackgroundEffectPage()) },
        "PrimitiveButtonStyle":                                                                     { _ in AnyView(PrimitiveButtonStyleProtocolPage()) },
        "PrimitiveButtonStyleConfiguration":                                                        { _ in AnyView(PrimitiveButtonStyleConfigurationPage()) },
        "ProgressViewStyle":                                                                        { _ in AnyView(ProgressViewStylePage()) },
        "ProgressViewStyleConfiguration":                                                           { _ in AnyView(ProgressViewStylePage()) },
        "Prominence":                                                                               { _ in AnyView(ProminenceTypePage()) },
        "PushWindowAction":                                                                         { _ in AnyView(PushWindowActionPage()) },
        "RedactionReasons":                                                                         { _ in AnyView(RedactionReasonsTypePage()) },
        "Reducing view modifier maintenance":                                                       { _ in AnyView(ReducingViewModifierMaintenancePage()) },
        "RefreshAction":                                                                            { _ in AnyView(RefreshActionTypePage()) },
        "Scene/defaultLaunchBehavior(_:)":                                                          { _ in AnyView(DefaultLaunchBehaviorPage()) },
        "Scene/defaultPosition(_:)":                                                                { _ in AnyView(DefaultPositionPage()) },
        "Scene/defaultSize(_:)":                                                                    { _ in AnyView(DefaultSizePage()) },
        "Scene/defaultSize(_:in:)":                                                                 { _ in AnyView(DefaultSizePage()) },
        "Scene/defaultSize(width:height:)":                                                         { _ in AnyView(DefaultSizePage()) },
        "Scene/defaultSize(width:height:depth:)":                                                   { _ in AnyView(DefaultSizePage()) },
        "Scene/defaultSize(width:height:depth:in:)":                                                { _ in AnyView(DefaultSizePage()) },
        "Scene/defaultWindowPlacement(_:)":                                                         { _ in AnyView(WindowPlacementPage()) },
        "Scene/persistentSystemOverlays(_:)":                                                       { _ in AnyView(PersistentSystemOverlaysPage()) },
        "Scene/restorationBehavior(_:)":                                                            { _ in AnyView(RestorationBehaviorPage()) },
        "Scene/windowBackgroundDragBehavior(_:)":                                                   { _ in AnyView(WindowBackgroundDragBehaviorPage()) },
        "Scene/windowIdealPlacement(_:)":                                                           { _ in AnyView(WindowPlacementPage()) },
        "Scene/windowIdealSize(_:)":                                                                { _ in AnyView(WindowIdealSizePage()) },
        "Scene/windowLevel(_:)":                                                                    { _ in AnyView(WindowLevelPage()) },
        "Scene/windowManagerRole(_:)":                                                              { _ in AnyView(WindowManagerRolePage()) },
        "Scene/windowResizability(_:)":                                                             { _ in AnyView(WindowResizabilityPage()) },
        "Scene/windowStyle(_:)":                                                                    { _ in AnyView(WindowStylePage()) },
        "Scene/windowToolbarLabelStyle(_:)":                                                        { _ in AnyView(WindowToolbarLabelStylePage()) },
        "Scene/windowToolbarLabelStyle(fixed:)":                                                    { _ in AnyView(WindowToolbarLabelStylePage()) },
        "Scene/windowToolbarStyle(_:)":                                                             { _ in AnyView(WindowToolbarStylePage()) },
        "SceneLaunchBehavior":                                                                      { _ in AnyView(DefaultLaunchBehaviorPage()) },
        "SceneRestorationBehavior":                                                                 { _ in AnyView(RestorationBehaviorPage()) },
        "Scoping a search operation":                                                               { _ in AnyView(ScopingSearchOperationPage()) },
        "SidebarRowSize":                                                                           { _ in AnyView(SidebarRowSizePage()) },
        "SubscriptionView":                                                                         { _ in AnyView(SubscriptionViewPage()) },
        "Suggesting search terms":                                                                  { _ in AnyView(SuggestingSearchTermsPage()) },
        "SurroundingsEffect":                                                                       { _ in AnyView(SurroundingsEffectTypePage()) },
        "Tab":                                                                                      { _ in AnyView(TabPage()) },
        "TabContent":                                                                               { _ in AnyView(TabContentPage()) },
        "TabContentBuilder":                                                                        { _ in AnyView(TabContentBuilderPage()) },
        "TabCustomizationBehavior":                                                                 { _ in AnyView(TabCustomizationBehaviorPage()) },
        "TabPlacement":                                                                             { _ in AnyView(TabPlacementPage()) },
        "TabRole":                                                                                  { _ in AnyView(TabRolePage()) },
        "TabSection":                                                                               { _ in AnyView(TabSectionPage()) },
        "TabView":                                                                                  { _ in AnyView(TabViewPage()) },
        "TabViewCustomization":                                                                     { _ in AnyView(TabViewCustomizationPage()) },
        "TabViewStyle":                                                                             { _ in AnyView(TabViewStylePage()) },
        "Table":                                                                                    { _ in AnyView(TablePage()) },
        "TableColumn":                                                                              { _ in AnyView(TableColumnPage()) },
        "TableStyle":                                                                               { _ in AnyView(TableStyleProtocolPage()) },
        "TableStyleConfiguration":                                                                  { _ in AnyView(TableStyleConfigurationPage()) },
        "TextEditorStyle":                                                                          { _ in AnyView(TextEditorStylePage()) },
        "TextEditorStyleConfiguration":                                                             { _ in AnyView(TextEditorStylePage()) },
        "TextFieldStyle":                                                                           { _ in AnyView(TextFieldStylePage()) },
        "ToggleStyle":                                                                              { _ in AnyView(ToggleStylePage()) },
        "ToggleStyleConfiguration":                                                                 { _ in AnyView(ToggleStylePage()) },
        "Typography":                                                                               { _ in AnyView(TypographyPage()) },
        "Understanding the navigation stack":                                                       { _ in AnyView(UnderstandingNavigationStackPage()) },
        "UtilityWindow":                                                                            { _ in AnyView(UtilityWindowPage()) },
        "VSplitView":                                                                               { _ in AnyView(VSplitViewPage()) },
        "View":                                                                                     { _ in AnyView(ViewProtocolPage()) },
        "View/alert(_:isPresented:actions:)":                                                       { _ in AnyView(AlertIsPresentedPage()) },
        "View/alert(_:isPresented:presenting:actions:)":                                            { _ in AnyView(AlertPresentingPage()) },
        "View/alert(isPresented:error:actions:)":                                                   { _ in AnyView(AlertErrorPage()) },
        "View/alternatingRowBackgrounds(_:)":                                                       { _ in AnyView(AlternatingRowBackgroundsPage()) },
        "View/badge(_:)":                                                                           { _ in AnyView(BadgePage()) },
        "View/badgeProminence(_:)":                                                                 { _ in AnyView(BadgeProminencePage()) },
        "View/body-8kl5o":                                                                          { _ in AnyView(ViewBodyPage()) },
        "View/buttonStyle(_:)":                                                                     { _ in AnyView(ButtonStyleModifierPage()) },
        "View/confirmationDialog(_:isPresented:titleVisibility:actions:)":                          { _ in AnyView(ConfirmationDialogIsPresentedPage()) },
        "View/confirmationDialog(_:isPresented:titleVisibility:presenting:actions:)":               { _ in AnyView(ConfirmationDialogPresentingPage()) },
        "View/controlGroupStyle(_:)":                                                               { _ in AnyView(ControlGroupStylePage()) },
        "View/datePickerStyle(_:)":                                                                 { _ in AnyView(DatePickerStylePage()) },
        "View/deleteDisabled(_:)":                                                                  { _ in AnyView(DeleteDisabledPage()) },
        "View/disabled(_:)":                                                                        { _ in AnyView(DisabledPage()) },
        "View/disclosureGroupStyle(_:)":                                                            { _ in AnyView(DisclosureGroupStylePage()) },
        "View/dismissalConfirmationDialog(_:shouldPresent:actions:)":                               { _ in AnyView(DismissalConfirmationDialogPage()) },
        "View/equatable()":                                                                         { _ in AnyView(EquatablePage()) },
        "View/fileExporter(isPresented:document:contentType:defaultFilename:onCompletion:)":        { _ in AnyView(FileExporterPage()) },
        "View/fileImporter(isPresented:allowedContentTypes:allowsMultipleSelection:onCompletion:)": { _ in AnyView(FileImporterPage()) },
        "View/fileMover(isPresented:file:onCompletion:)":                                           { _ in AnyView(FileMoverPage()) },
        "View/formStyle(_:)":                                                                       { _ in AnyView(FormStylePage()) },
        "View/fullScreenCover(isPresented:onDismiss:content:)":                                     { _ in AnyView(FullScreenCoverIsPresentedPage()) },
        "View/fullScreenCover(item:onDismiss:content:)":                                            { _ in AnyView(FullScreenCoverItemPage()) },
        "View/gaugeStyle(_:)":                                                                      { _ in AnyView(GaugeStylePage()) },
        "View/glassBackgroundEffect(displayMode:)":                                                 { _ in AnyView(GlassBackgroundEffectPage()) },
        "View/glassBackgroundEffect(in:displayMode:)":                                              { _ in AnyView(GlassBackgroundEffectPage()) },
        "View/glassEffect(_:in:)":                                                                  { _ in AnyView(GlassEffectPage()) },
        "View/groupBoxStyle(_:)":                                                                   { _ in AnyView(GroupBoxStylePage()) },
        "View/headerProminence(_:)":                                                                { _ in AnyView(HeaderProminencePage()) },
        "View/help(_:)":                                                                            { _ in AnyView(HelpPage()) },
        "View/hidden()":                                                                            { _ in AnyView(HiddenPage()) },
        "View/id(_:)":                                                                              { _ in AnyView(IDPage()) },
        "View/indexViewStyle(_:)":                                                                  { _ in AnyView(IndexViewStylePage()) },
        "View/interactionActivityTrackingTag(_:)":                                                  { _ in AnyView(InteractionActivityTrackingTagPage()) },
        "View/invalidatableContent(_:)":                                                            { _ in AnyView(InvalidatableContentPage()) },
        "View/labelStyle(_:)":                                                                      { _ in AnyView(LabelStylePage()) },
        "View/labeledContentStyle(_:)":                                                             { _ in AnyView(LabeledContentStylePage()) },
        "View/labelsHidden()":                                                                      { _ in AnyView(LabelsHiddenPage()) },
        "View/labelsVisibility(_:)":                                                                { _ in AnyView(LabelsVisibilityPage()) },
        "View/listItemTint(_:)":                                                                    { _ in AnyView(ListItemTintPage()) },
        "View/listRowBackground(_:)":                                                               { _ in AnyView(ListRowBackgroundPage()) },
        "View/listRowHoverEffect(_:)":                                                              { _ in AnyView(ListRowHoverEffectPage()) },
        "View/listRowHoverEffectDisabled(_:)":                                                      { _ in AnyView(ListRowHoverEffectDisabledPage()) },
        "View/listRowInsets(_:)":                                                                   { _ in AnyView(ListRowInsetsPage()) },
        "View/listRowSeparator(_:edges:)":                                                          { _ in AnyView(ListRowSeparatorPage()) },
        "View/listRowSeparatorTint(_:edges:)":                                                      { _ in AnyView(ListRowSeparatorTintPage()) },
        "View/listRowSpacing(_:)":                                                                  { _ in AnyView(ListRowSpacingPage()) },
        "View/listSectionIndexVisibility(_:)":                                                      { _ in AnyView(ListSectionIndexVisibilityPage()) },
        "View/listSectionMargins(_:_:)":                                                            { _ in AnyView(ListSectionMarginsPage()) },
        "View/listSectionSeparator(_:edges:)":                                                      { _ in AnyView(ListSectionSeparatorPage()) },
        "View/listSectionSeparatorTint(_:edges:)":                                                  { _ in AnyView(ListSectionSeparatorTintPage()) },
        "View/listSectionSpacing(_:)":                                                              { _ in AnyView(ListSectionSpacingPage()) },
        "View/listStyle(_:)":                                                                       { _ in AnyView(ListStyleModifierPage()) },
        "View/menuIndicator(_:)":                                                                   { _ in AnyView(MenuIndicatorPage()) },
        "View/menuStyle(_:)":                                                                       { _ in AnyView(MenuStylePage()) },
        "View/modifier(_:)":                                                                        { _ in AnyView(ViewModifierApplyPage()) },
        "View/moveDisabled(_:)":                                                                    { _ in AnyView(MoveDisabledPage()) },
        "View/navigationDestination(for:destination:)":                                             { _ in AnyView(NavigationDestinationPage()) },
        "View/navigationDestination(isPresented:destination:)":                                     { _ in AnyView(NavigationDestinationIsPresentedPage()) },
        "View/navigationDestination(item:destination:)":                                            { _ in AnyView(NavigationDestinationItemPage()) },
        "View/navigationDocument(_:)":                                                              { _ in AnyView(NavigationDocumentPage()) },
        "View/navigationDocument(_:preview:)":                                                      { _ in AnyView(NavigationDocumentPreviewPage()) },
        "View/navigationSplitViewColumnWidth(_:)":                                                  { _ in AnyView(NavigationSplitViewColumnWidthPage()) },
        "View/navigationSplitViewColumnWidth(min:ideal:max:)":                                      { _ in AnyView(NavigationSplitViewColumnWidthFlexiblePage()) },
        "View/navigationSplitViewStyle(_:)":                                                        { _ in AnyView(NavigationSplitViewStylePage()) },
        "View/navigationSubtitle(_:)":                                                              { _ in AnyView(NavigationSubtitlePage()) },
        "View/navigationTitle(_:)":                                                                 { _ in AnyView(NavigationTitlePage()) },
        "View/onAppear(perform:)":                                                                  { _ in AnyView(OnAppearPage()) },
        "View/onDisappear(perform:)":                                                               { _ in AnyView(OnDisappearPage()) },
        "View/opacity(_:)":                                                                         { _ in AnyView(OpacityPage()) },
        "View/persistentSystemOverlays(_:)":                                                        { _ in AnyView(PersistentSystemOverlaysPage()) },
        "View/pickerStyle(_:)":                                                                     { _ in AnyView(PickerStylePage()) },
        "View/popover(isPresented:attachmentAnchor:arrowEdge:content:)":                            { _ in AnyView(PopoverIsPresentedPage()) },
        "View/popover(item:attachmentAnchor:arrowEdge:content:)":                                   { _ in AnyView(PopoverItemPage()) },
        "View/preferredColorScheme(_:)":                                                            { _ in AnyView(PreferredColorSchemePage()) },
        "View/preferredSurroundingsEffect(_:)":                                                     { _ in AnyView(PreferredSurroundingsEffectPage()) },
        "View/presentedWindowStyle(_:)":                                                            { _ in AnyView(PresentedWindowStylePage()) },
        "View/presentedWindowToolbarStyle(_:)":                                                     { _ in AnyView(PresentedWindowToolbarStylePage()) },
        "View/privacySensitive(_:)":                                                                { _ in AnyView(PrivacySensitivePage()) },
        "View/progressViewStyle(_:)":                                                               { _ in AnyView(ProgressViewStylePage()) },
        "View/redacted(reason:)":                                                                   { _ in AnyView(RedactedPage()) },
        "View/refreshable(action:)":                                                                { _ in AnyView(RefreshablePage()) },
        "View/searchable(text:editableTokens:isPresented:placement:prompt:token:)":                 { _ in AnyView(SearchableEditableTokensIsPresentedPage()) },
        "View/searchable(text:editableTokens:placement:prompt:token:)":                             { _ in AnyView(SearchableEditableTokensPage()) },
        "View/searchable(text:isPresented:placement:prompt:)":                                      { _ in AnyView(SearchableIsPresentedPage()) },
        "View/searchable(text:placement:prompt:)":                                                  { _ in AnyView(SearchableTextPage()) },
        "View/searchable(text:tokens:isPresented:placement:prompt:token:)":                         { _ in AnyView(SearchableTokensIsPresentedPage()) },
        "View/searchable(text:tokens:placement:prompt:token:)":                                     { _ in AnyView(SearchableTokensPage()) },
        "View/searchable(text:tokens:suggestedTokens:isPresented:placement:prompt:token:)":         { _ in AnyView(SearchableSuggestedTokensIsPresentedPage()) },
        "View/searchable(text:tokens:suggestedTokens:placement:prompt:token:)":                     { _ in AnyView(SearchableSuggestedTokensPage()) },
        "View/sectionActions(content:)":                                                            { _ in AnyView(SectionActionsPage()) },
        "View/sectionIndexLabel(_:)":                                                               { _ in AnyView(SectionIndexLabelPage()) },
        "View/selectionDisabled(_:)":                                                               { _ in AnyView(SelectionDisabledPage()) },
        "View/sheet(isPresented:onDismiss:content:)":                                               { _ in AnyView(SheetIsPresentedPage()) },
        "View/sheet(item:onDismiss:content:)":                                                      { _ in AnyView(SheetItemPage()) },
        "View/signInWithAppleButtonStyle(_:)":                                                      { _ in AnyView(SignInWithAppleButtonStylePage()) },
        "View/statusBarHidden(_:)":                                                                 { _ in AnyView(StatusBarHiddenPage()) },
        "View/swipeActions(edge:allowsFullSwipe:content:)":                                         { _ in AnyView(SwipeActionsPage()) },
        "View/tabViewCustomization(_:)":                                                            { _ in AnyView(TabViewCustomizationModifierPage()) },
        "View/tabViewSidebarBottomBar(content:)":                                                   { _ in AnyView(TabViewSidebarBottomBarPage()) },
        "View/tabViewSidebarFooter(content:)":                                                      { _ in AnyView(TabViewSidebarFooterPage()) },
        "View/tabViewSidebarHeader(content:)":                                                      { _ in AnyView(TabViewSidebarHeaderPage()) },
        "View/tabViewStyle(_:)":                                                                    { _ in AnyView(TabViewStylePage()) },
        "View/tableStyle(_:)":                                                                      { _ in AnyView(TableStyleModifierPage()) },
        "View/tag(_:includeOptional:)":                                                             { _ in AnyView(TagPage()) },
        "View/textEditorStyle(_:)":                                                                 { _ in AnyView(TextEditorStylePage()) },
        "View/textFieldStyle(_:)":                                                                  { _ in AnyView(TextFieldStylePage()) },
        "View/toggleStyle(_:)":                                                                     { _ in AnyView(ToggleStylePage()) },
        "View/toolbar(_:for:)":                                                                     { _ in AnyView(ToolbarVisibilityForPage()) },
        "View/toolbar(content:)":                                                                   { _ in AnyView(ToolbarContentPage()) },
        "View/unredacted()":                                                                        { _ in AnyView(UnredactedPage()) },
        "View/windowDismissBehavior(_:)":                                                           { _ in AnyView(WindowInteractionBehaviorPage()) },
        "View/windowFullScreenBehavior(_:)":                                                        { _ in AnyView(WindowInteractionBehaviorPage()) },
        "View/windowMinimizeBehavior(_:)":                                                          { _ in AnyView(WindowInteractionBehaviorPage()) },
        "View/windowResizeBehavior(_:)":                                                            { _ in AnyView(WindowInteractionBehaviorPage()) },
        "View/windowToolbarFullScreenVisibility(_:)":                                               { _ in AnyView(WindowToolbarFullScreenVisibilityPage()) },
        "ViewBuilder":                                                                              { _ in AnyView(ViewBuilderPage()) },
        "ViewModifier":                                                                             { _ in AnyView(ViewModifierProtocolPage()) },
        "Visibility":                                                                               { _ in AnyView(VisibilityTypePage()) },
        "Window":                                                                                   { _ in AnyView(WindowPage()) },
        "WindowGroup":                                                                              { _ in AnyView(WindowGroupPage()) },
        "WindowIdealSize":                                                                          { _ in AnyView(WindowIdealSizePage()) },
        "WindowInteractionBehavior":                                                                { _ in AnyView(WindowInteractionBehaviorPage()) },
        "WindowLayoutRoot":                                                                         { _ in AnyView(WindowLayoutRootPage()) },
        "WindowLevel":                                                                              { _ in AnyView(WindowLevelPage()) },
        "WindowManagerRole":                                                                        { _ in AnyView(WindowManagerRolePage()) },
        "WindowPlacement":                                                                          { _ in AnyView(WindowPlacementPage()) },
        "WindowPlacementContext":                                                                   { _ in AnyView(WindowPlacementPage()) },
        "WindowProxy":                                                                              { _ in AnyView(WindowProxyPage()) },
        "WindowResizability":                                                                       { _ in AnyView(WindowResizabilityPage()) },
        "WindowStyle":                                                                              { _ in AnyView(WindowStylePage()) },
        "WindowToolbarFullScreenVisibility":                                                        { _ in AnyView(WindowToolbarFullScreenVisibilityPage()) },
        "WindowToolbarStyle":                                                                       { _ in AnyView(WindowToolbarStylePage()) },
        "WindowVisibilityToggle":                                                                   { _ in AnyView(WindowVisibilityTogglePage()) }
    ]
}
