import SwiftUI

@MainActor
enum PageRegistry {
    static func view(for leaf: Leaf) -> AnyView {
        switch leaf.pageBuilder {
        case .placeholder:
            return AnyView(PlaceholderPage(leaf: leaf))
        case .real(let symbol):
            if let builder = realPages[symbol] {
                return builder(leaf)
            }
            return AnyView(PlaceholderPage(leaf: leaf))
        }
    }

    private static let realPages: [String: (Leaf) -> AnyView] = [
        "AlternatingRowBackgroundBehavior":                                  { _ in AnyView(AlternatingRowBackgroundBehaviorTypePage()) },
        "AnyTabContent":                                                     { _ in AnyView(AnyTabContentPage()) },
        "BackgroundProminence":                                              { _ in AnyView(BackgroundProminenceTypePage()) },
        "BadgeProminence":                                                   { _ in AnyView(BadgeProminencePage()) },
        "Bringing multiple windows to your SwiftUI app":                     { _ in AnyView(BringingMultipleWindowsToYourSwiftUIAppPage()) },
        "Bringing robust navigation structure to your SwiftUI app":          { _ in AnyView(BringingRobustNavigationStructurePage()) },
        "ControlActiveState":                                                { _ in AnyView(ControlActiveStatePage()) },
        "Customizing window styles and state-restoration behavior in macOS": { _ in AnyView(CustomizingWindowStylesAndStateRestorationBehaviorInMacOSPage()) },
        "DisclosureGroup":                                                   { _ in AnyView(DisclosureGroupPage()) },
        "DismissAction":                                                     { _ in AnyView(DismissPage()) },
        "DismissBehavior":                                                   { _ in AnyView(DismissPage()) },
        "DismissWindowAction":                                               { _ in AnyView(DismissWindowPage()) },
        "DisplayProxy":                                                      { _ in AnyView(DisplayProxyPage()) },
        "Displaying data in lists":                                          { _ in AnyView(DisplayingDataInListsPage()) },
        "EditActions":                                                       { _ in AnyView(EditActionsTypePage()) },
        "EditMode":                                                          { _ in AnyView(EditModeTypePage()) },
        "EditableCollectionContent":                                         { _ in AnyView(EditableCollectionContentTypePage()) },
        "Enhancing your app content with tab navigation":                    { _ in AnyView(EnhancingTabNavigationPage()) },
        "EnvironmentValues/dismiss":                                         { _ in AnyView(DismissPage()) },
        "EnvironmentValues/dismissWindow":                                   { _ in AnyView(DismissWindowPage()) },
        "EnvironmentValues/openWindow":                                      { _ in AnyView(OpenWindowPage()) },
        "EnvironmentValues/sidebarRowSize":                                  { _ in AnyView(SidebarRowSizeEnvironmentPage()) },
        "EnvironmentValues/supportsMultipleWindows":                         { _ in AnyView(SupportsMultipleWindowsPage()) },
        "ForEach":                                                           { _ in AnyView(ForEachPage()) },
        "HSplitView":                                                        { _ in AnyView(HSplitViewPage()) },
        "IndexedIdentifierCollection":                                       { _ in AnyView(IndexedIdentifierCollectionTypePage()) },
        "List":                                                              { _ in AnyView(ListPage()) },
        "ListItemTint":                                                      { _ in AnyView(ListItemTintPage()) },
        "ListSectionSpacing":                                                { _ in AnyView(ListSectionSpacingPage()) },
        "Migrating to new navigation types":                                 { _ in AnyView(MigratingToNewNavigationTypesPage()) },
        "NavigationLink":                                                    { _ in AnyView(NavigationLinkPage()) },
        "NavigationPath":                                                    { _ in AnyView(NavigationPathPage()) },
        "NavigationSplitView":                                               { _ in AnyView(NavigationSplitViewPage()) },
        "NavigationSplitViewColumn":                                         { _ in AnyView(NavigationSplitViewColumnPage()) },
        "NavigationSplitViewStyle":                                          { _ in AnyView(NavigationSplitViewStylePage()) },
        "NavigationSplitViewVisibility":                                     { _ in AnyView(NavigationSplitViewVisibilityPage()) },
        "NavigationStack":                                                   { _ in AnyView(NavigationStackPage()) },
        "NavigationView":                                                    { _ in AnyView(NavigationViewPage()) },
        "OpenWindowAction":                                                  { _ in AnyView(OpenWindowPage()) },
        "OutlineGroup":                                                      { _ in AnyView(OutlineGroupPage()) },
        "Prominence":                                                        { _ in AnyView(ProminenceTypePage()) },
        "PushWindowAction":                                                  { _ in AnyView(PushWindowActionPage()) },
        "RefreshAction":                                                     { _ in AnyView(RefreshActionTypePage()) },
        "Scene/defaultLaunchBehavior(_:)":                                   { _ in AnyView(DefaultLaunchBehaviorPage()) },
        "Scene/defaultPosition(_:)":                                         { _ in AnyView(DefaultPositionPage()) },
        "Scene/defaultSize(_:)":                                             { _ in AnyView(DefaultSizePage()) },
        "Scene/defaultSize(_:in:)":                                          { _ in AnyView(DefaultSizePage()) },
        "Scene/defaultSize(width:height:)":                                  { _ in AnyView(DefaultSizePage()) },
        "Scene/defaultSize(width:height:depth:)":                            { _ in AnyView(DefaultSizePage()) },
        "Scene/defaultSize(width:height:depth:in:)":                         { _ in AnyView(DefaultSizePage()) },
        "Scene/defaultWindowPlacement(_:)":                                  { _ in AnyView(WindowPlacementPage()) },
        "Scene/persistentSystemOverlays(_:)":                                { _ in AnyView(PersistentSystemOverlaysPage()) },
        "Scene/restorationBehavior(_:)":                                     { _ in AnyView(RestorationBehaviorPage()) },
        "Scene/windowBackgroundDragBehavior(_:)":                            { _ in AnyView(WindowBackgroundDragBehaviorPage()) },
        "Scene/windowIdealPlacement(_:)":                                    { _ in AnyView(WindowPlacementPage()) },
        "Scene/windowIdealSize(_:)":                                         { _ in AnyView(WindowIdealSizePage()) },
        "Scene/windowLevel(_:)":                                             { _ in AnyView(WindowLevelPage()) },
        "Scene/windowManagerRole(_:)":                                       { _ in AnyView(WindowManagerRolePage()) },
        "Scene/windowResizability(_:)":                                      { _ in AnyView(WindowResizabilityPage()) },
        "Scene/windowStyle(_:)":                                             { _ in AnyView(WindowStylePage()) },
        "Scene/windowToolbarLabelStyle(_:)":                                 { _ in AnyView(WindowToolbarLabelStylePage()) },
        "Scene/windowToolbarLabelStyle(fixed:)":                             { _ in AnyView(WindowToolbarLabelStylePage()) },
        "Scene/windowToolbarStyle(_:)":                                      { _ in AnyView(WindowToolbarStylePage()) },
        "SceneLaunchBehavior":                                               { _ in AnyView(DefaultLaunchBehaviorPage()) },
        "SceneRestorationBehavior":                                          { _ in AnyView(RestorationBehaviorPage()) },
        "SidebarRowSize":                                                    { _ in AnyView(SidebarRowSizePage()) },
        "Tab":                                                               { _ in AnyView(TabPage()) },
        "TabContent":                                                        { _ in AnyView(TabContentPage()) },
        "TabContentBuilder":                                                 { _ in AnyView(TabContentBuilderPage()) },
        "TabCustomizationBehavior":                                          { _ in AnyView(TabCustomizationBehaviorPage()) },
        "TabPlacement":                                                      { _ in AnyView(TabPlacementPage()) },
        "TabRole":                                                           { _ in AnyView(TabRolePage()) },
        "TabSection":                                                        { _ in AnyView(TabSectionPage()) },
        "TabView":                                                           { _ in AnyView(TabViewPage()) },
        "TabViewCustomization":                                              { _ in AnyView(TabViewCustomizationPage()) },
        "TabViewStyle":                                                      { _ in AnyView(TabViewStylePage()) },
        "Table":                                                             { _ in AnyView(TablePage()) },
        "TableColumn":                                                       { _ in AnyView(TableColumnPage()) },
        "Typography":                                                        { _ in AnyView(TypographyPage()) },
        "Understanding the navigation stack":                                { _ in AnyView(UnderstandingNavigationStackPage()) },
        "UtilityWindow":                                                     { _ in AnyView(UtilityWindowPage()) },
        "VSplitView":                                                        { _ in AnyView(VSplitViewPage()) },
        "View/alternatingRowBackgrounds(_:)":                                { _ in AnyView(AlternatingRowBackgroundsPage()) },
        "View/badge(_:)":                                                    { _ in AnyView(BadgePage()) },
        "View/badgeProminence(_:)":                                          { _ in AnyView(BadgeProminencePage()) },
        "View/deleteDisabled(_:)":                                           { _ in AnyView(DeleteDisabledPage()) },
        "View/headerProminence(_:)":                                         { _ in AnyView(HeaderProminencePage()) },
        "View/listItemTint(_:)":                                             { _ in AnyView(ListItemTintPage()) },
        "View/listRowBackground(_:)":                                        { _ in AnyView(ListRowBackgroundPage()) },
        "View/listRowHoverEffect(_:)":                                       { _ in AnyView(ListRowHoverEffectPage()) },
        "View/listRowHoverEffectDisabled(_:)":                               { _ in AnyView(ListRowHoverEffectDisabledPage()) },
        "View/listRowInsets(_:)":                                            { _ in AnyView(ListRowInsetsPage()) },
        "View/listRowSeparator(_:edges:)":                                   { _ in AnyView(ListRowSeparatorPage()) },
        "View/listRowSeparatorTint(_:edges:)":                               { _ in AnyView(ListRowSeparatorTintPage()) },
        "View/listRowSpacing(_:)":                                           { _ in AnyView(ListRowSpacingPage()) },
        "View/listSectionIndexVisibility(_:)":                               { _ in AnyView(ListSectionIndexVisibilityPage()) },
        "View/listSectionMargins(_:_:)":                                     { _ in AnyView(ListSectionMarginsPage()) },
        "View/listSectionSeparator(_:edges:)":                               { _ in AnyView(ListSectionSeparatorPage()) },
        "View/listSectionSeparatorTint(_:edges:)":                           { _ in AnyView(ListSectionSeparatorTintPage()) },
        "View/listSectionSpacing(_:)":                                       { _ in AnyView(ListSectionSpacingPage()) },
        "View/moveDisabled(_:)":                                             { _ in AnyView(MoveDisabledPage()) },
        "View/navigationDestination(for:destination:)":                      { _ in AnyView(NavigationDestinationPage()) },
        "View/navigationDestination(isPresented:destination:)":              { _ in AnyView(NavigationDestinationIsPresentedPage()) },
        "View/navigationDestination(item:destination:)":                     { _ in AnyView(NavigationDestinationItemPage()) },
        "View/navigationDocument(_:)":                                       { _ in AnyView(NavigationDocumentPage()) },
        "View/navigationDocument(_:preview:)":                               { _ in AnyView(NavigationDocumentPreviewPage()) },
        "View/navigationSplitViewColumnWidth(_:)":                           { _ in AnyView(NavigationSplitViewColumnWidthPage()) },
        "View/navigationSplitViewColumnWidth(min:ideal:max:)":               { _ in AnyView(NavigationSplitViewColumnWidthFlexiblePage()) },
        "View/navigationSplitViewStyle(_:)":                                 { _ in AnyView(NavigationSplitViewStylePage()) },
        "View/navigationSubtitle(_:)":                                       { _ in AnyView(NavigationSubtitlePage()) },
        "View/navigationTitle(_:)":                                          { _ in AnyView(NavigationTitlePage()) },
        "View/persistentSystemOverlays(_:)":                                 { _ in AnyView(PersistentSystemOverlaysPage()) },
        "View/presentedWindowStyle(_:)":                                     { _ in AnyView(PresentedWindowStylePage()) },
        "View/refreshable(action:)":                                         { _ in AnyView(RefreshablePage()) },
        "View/sectionActions(content:)":                                     { _ in AnyView(SectionActionsPage()) },
        "View/sectionIndexLabel(_:)":                                        { _ in AnyView(SectionIndexLabelPage()) },
        "View/selectionDisabled(_:)":                                        { _ in AnyView(SelectionDisabledPage()) },
        "View/swipeActions(edge:allowsFullSwipe:content:)":                  { _ in AnyView(SwipeActionsPage()) },
        "View/tabViewCustomization(_:)":                                     { _ in AnyView(TabViewCustomizationModifierPage()) },
        "View/tabViewSidebarBottomBar(content:)":                            { _ in AnyView(TabViewSidebarBottomBarPage()) },
        "View/tabViewSidebarFooter(content:)":                               { _ in AnyView(TabViewSidebarFooterPage()) },
        "View/tabViewSidebarHeader(content:)":                               { _ in AnyView(TabViewSidebarHeaderPage()) },
        "View/tabViewStyle(_:)":                                             { _ in AnyView(TabViewStylePage()) },
        "View/windowDismissBehavior(_:)":                                    { _ in AnyView(WindowInteractionBehaviorPage()) },
        "View/windowFullScreenBehavior(_:)":                                 { _ in AnyView(WindowInteractionBehaviorPage()) },
        "View/windowMinimizeBehavior(_:)":                                   { _ in AnyView(WindowInteractionBehaviorPage()) },
        "View/windowResizeBehavior(_:)":                                     { _ in AnyView(WindowInteractionBehaviorPage()) },
        "View/windowToolbarFullScreenVisibility(_:)":                        { _ in AnyView(WindowToolbarFullScreenVisibilityPage()) },
        "Window":                                                            { _ in AnyView(WindowPage()) },
        "WindowGroup":                                                       { _ in AnyView(WindowGroupPage()) },
        "WindowIdealSize":                                                   { _ in AnyView(WindowIdealSizePage()) },
        "WindowInteractionBehavior":                                         { _ in AnyView(WindowInteractionBehaviorPage()) },
        "WindowLayoutRoot":                                                  { _ in AnyView(WindowLayoutRootPage()) },
        "WindowLevel":                                                       { _ in AnyView(WindowLevelPage()) },
        "WindowManagerRole":                                                 { _ in AnyView(WindowManagerRolePage()) },
        "WindowPlacement":                                                   { _ in AnyView(WindowPlacementPage()) },
        "WindowPlacementContext":                                            { _ in AnyView(WindowPlacementPage()) },
        "WindowProxy":                                                       { _ in AnyView(WindowProxyPage()) },
        "WindowResizability":                                                { _ in AnyView(WindowResizabilityPage()) },
        "WindowStyle":                                                       { _ in AnyView(WindowStylePage()) },
        "WindowToolbarFullScreenVisibility":                                 { _ in AnyView(WindowToolbarFullScreenVisibilityPage()) },
        "WindowToolbarStyle":                                                { _ in AnyView(WindowToolbarStylePage()) },
        "WindowVisibilityToggle":                                            { _ in AnyView(WindowVisibilityTogglePage()) }
    ]
}
