#!/bin/bash
# Generates Swift catalog data files from URL manifests.
# Output: Catalog+SwiftUI.swift, Catalog+AppKit.swift in SwiftKit/SwiftKit/Catalog/
#
# Usage: ./generate-catalog.sh
# Idempotent — overwrites the two output files.

set -eo pipefail

REPO_ROOT="/Users/nathantaichman/The Studio/Projects/SwiftKit"
DOC_ROOT="$REPO_ROOT/Documentation"
OUT_ROOT="$REPO_ROOT/SwiftKit/Catalog"

# --- SwiftUI inclusion / exclusion ------------------------------------------------

SWIFTUI_EXCLUDED=(
    "Environment values" "Focus" "Documents" "Previews in Xcode"
    "App extensions" "System events" "Model data" "UIKit integration"
    "Accessibility fundamentals" "Preferences" "Persistent storage"
    "App organization" "Clipboard" "WatchKit integration" "Articles" "Essentials"
)

# Per-symbol blocklist (full URL slug) for SwiftUI
SWIFTUI_LEAF_BLOCK=(
    "anyview" "tupleview" "emptyview" "equatableview"
    "nsviewrepresentable" "nsviewcontrollerrepresentable"
    "nsviewrepresentablecontext" "nsviewcontrollerrepresentablecontext"
)

# --- AppKit inclusion / exclusion ------------------------------------------------

APPKIT_EXCLUDED=(
    "Cocoa bindings" "Resource management" "App extensions"
    "Sound, speech, and haptics" "Drag and drop"
    "Reference (enumerations, constants, data types, macros)" "Deprecated symbols"
    "App structure" "Documents, data, and pasteboard"
    "Mouse, keyboard, and trackpad" "Printing" "Continuity Camera"
)

# --- Helpers ---------------------------------------------------------------------

slugify() {
    echo "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

# Convert a symbol name to a Swift-safe identifier base (no special chars)
swift_id_safe() {
    echo "$1" | sed -E 's/[^a-zA-Z0-9]+/_/g'
}

# Lookup framework "Swift availability" line from a captured doc — return e.g. "macOS 13.0+" or empty
get_macos_avail() {
    local doc="$1"
    [ -f "$doc" ] || { echo ""; return; }
    awk '
        /^## Availability/ { in_avail = 1; next }
        in_avail && /^## / { exit }
        in_avail && /^- macOS/ { print; exit }
    ' "$doc" | sed -E 's/^- //; s/ \(deprecated.*\)//'
}

# Escape a string for Swift literal
swift_esc() {
    printf '%s' "$1" | sed -E 's/\\/\\\\/g; s/"/\\"/g'
}

# --- SwiftUI generation ----------------------------------------------------------

write_swiftui() {
    local out="$OUT_ROOT/Catalog+SwiftUI.swift"
    {
        echo "import Foundation"
        echo ""
        echo "// Generated by Documentation/_index/generate-catalog.sh"
        echo "// Source: Documentation/_links/swiftui-urls.md"
        echo "// Each folder is a private let to keep type-checker happy (L-011)."
        echo ""
    } > "$out"

    local current_section=""
    local section_id=""
    local section_slug=""
    local in_section=0
    local folder_var=""
    local section_count=0
    declare -a folder_vars=()
    declare -a folder_titles=()
    declare -a folder_slugs=()
    declare -a children_lines=()

    while IFS= read -r line; do
        if [[ "$line" =~ ^"## "(.*) ]]; then
            # flush previous section
            if [ -n "$current_section" ] && [ "$in_section" = "1" ]; then
                emit_swiftui_folder "$current_section" "$section_slug" "$folder_var" "${children_lines[@]}" >> "$out"
                folder_vars+=("$folder_var")
                folder_titles+=("$current_section")
                folder_slugs+=("$section_slug")
            fi
            current_section="${BASH_REMATCH[1]}"
            section_slug=$(slugify "$current_section")
            folder_var="swiftUI_$(swift_id_safe "$section_slug")"
            children_lines=()
            in_section=0
            # Skip excluded
            for ex in "${SWIFTUI_EXCLUDED[@]}"; do
                if [ "$current_section" = "$ex" ]; then
                    in_section=2
                    break
                fi
            done
            [ "$in_section" = "0" ] && in_section=1
        elif [[ "$line" =~ ^"- "\[(.+)\]\((.+)\)$ ]] && [ "$in_section" = "1" ]; then
            local sym_name="${BASH_REMATCH[1]}"
            local url="${BASH_REMATCH[2]}"
            local sym_slug=$(echo "$url" | sed -E 's:/$::; s:.*/::; s:[?#].*::')
            # Apply per-symbol blocklist
            local skip=0
            for blk in "${SWIFTUI_LEAF_BLOCK[@]}"; do
                if [ "$sym_slug" = "$blk" ]; then skip=1; break; fi
            done
            [ "$skip" = "1" ] && continue
            local doc_path="Documentation/SwiftUI/$section_slug/$sym_slug.md"
            local abs="$DOC_ROOT/SwiftUI/$section_slug/$sym_slug.md"
            local avail=""
            [ -f "$abs" ] && avail=$(get_macos_avail "$abs")
            local leaf_id="swiftui.$section_slug.$sym_slug"
            local sym_disp=$(swift_esc "$sym_name")
            children_lines+=("    .leaf(Leaf(id: \"$leaf_id\", displayName: \"$sym_disp\", apiSignature: \"$sym_disp\", framework: .swiftUI, docMarkdownPath: \"$doc_path\", availability: $([ -n "$avail" ] && echo "\"$avail\"" || echo nil), pageBuilder: .placeholder))")
        fi
    done < "$DOC_ROOT/_links/swiftui-urls.md"

    # flush last section
    if [ -n "$current_section" ] && [ "$in_section" = "1" ]; then
        emit_swiftui_folder "$current_section" "$section_slug" "$folder_var" "${children_lines[@]}" >> "$out"
        folder_vars+=("$folder_var")
        folder_titles+=("$current_section")
        folder_slugs+=("$section_slug")
    fi

    # Section assembly
    {
        echo ""
        echo "let swiftUITree: CatalogNode = .section(SectionNode("
        echo "    id: \"swiftui\","
        echo "    title: \"SwiftUI\","
        echo "    symbolName: \"swift\","
        echo "    children: ["
        for v in "${folder_vars[@]}"; do
            echo "        $v,"
        done
        echo "    ]"
        echo "))"
    } >> "$out"

    echo "Wrote $out (${#folder_vars[@]} folders)"
}

emit_swiftui_folder() {
    local title="$1"
    local slug="$2"
    local varname="$3"
    shift 3
    local titleEsc=$(swift_esc "$title")
    echo ""
    echo "private let $varname: CatalogNode = .folder(Folder("
    echo "    id: \"swiftui.$slug\","
    echo "    title: \"$titleEsc\","
    echo "    symbolName: \"folder\","
    echo "    children: ["
    for child in "$@"; do
        echo "$child,"
    done
    echo "    ]"
    echo "))"
}

# --- AppKit generation -----------------------------------------------------------

write_appkit() {
    local out="$OUT_ROOT/Catalog+AppKit.swift"
    {
        echo "import Foundation"
        echo ""
        echo "// Generated by Documentation/_index/generate-catalog.sh"
        echo "// Source: Documentation/_links/appkit-urls.md"
        echo "// Each section is a private let to keep type-checker happy (L-011)."
        echo ""
    } > "$out"

    local current_section=""
    local section_slug=""
    local current_sub=""
    local in_section=0
    declare -a folder_vars=()
    declare -a sub_lines=()    # subheading literals for current section
    declare -a leaf_lines=()   # leaves for current sub
    local sub_count=0

    flush_sub() {
        if [ -n "$current_sub" ] && [ "${#leaf_lines[@]}" -gt 0 ]; then
            local sub_id="appkit.$section_slug.$(slugify "$current_sub")"
            local subTitleEsc=$(swift_esc "$current_sub")
            local literal="    .subheading(Subheading(id: \"$sub_id\", title: \"$subTitleEsc\", children: ["
            for ll in "${leaf_lines[@]}"; do
                literal+=$'\n'"        $ll,"
            done
            literal+=$'\n'"    ]))"
            sub_lines+=("$literal")
            leaf_lines=()
        fi
    }

    flush_section() {
        if [ -n "$current_section" ] && [ "$in_section" = "1" ]; then
            flush_sub
            local section_var="appKit_$(swift_id_safe "$section_slug")"
            local titleEsc=$(swift_esc "$current_section")
            {
                echo ""
                echo "private let $section_var: CatalogNode = .folder(Folder("
                echo "    id: \"appkit.$section_slug\","
                echo "    title: \"$titleEsc\","
                echo "    symbolName: \"folder\","
                echo "    children: ["
                for sl in "${sub_lines[@]}"; do
                    echo "$sl,"
                done
                echo "    ]"
                echo "))"
            } >> "$out"
            folder_vars+=("$section_var")
        fi
        sub_lines=()
        current_sub=""
    }

    while IFS= read -r line; do
        if [[ "$line" =~ ^"## "(.*) ]]; then
            flush_section
            current_section="${BASH_REMATCH[1]}"
            section_slug=$(slugify "$current_section")
            in_section=1
            for ex in "${APPKIT_EXCLUDED[@]}"; do
                if [ "$current_section" = "$ex" ]; then in_section=2; break; fi
            done
        elif [[ "$line" =~ ^"### "(.*) ]] && [ "$in_section" = "1" ]; then
            flush_sub
            current_sub="${BASH_REMATCH[1]}"
        elif [[ "$line" =~ ^"- "\[(.+)\]\((.+)\)$ ]] && [ "$in_section" = "1" ]; then
            local sym_name="${BASH_REMATCH[1]}"
            local url="${BASH_REMATCH[2]}"
            local sym_slug=$(echo "$url" | sed -E 's:/$::; s:.*/::; s:[?#].*::')
            local doc_path="Documentation/AppKit/$section_slug/$sym_slug.md"
            local abs="$DOC_ROOT/AppKit/$section_slug/$sym_slug.md"
            local avail=""
            [ -f "$abs" ] && avail=$(get_macos_avail "$abs")
            local sub_part=""
            [ -n "$current_sub" ] && sub_part=$(slugify "$current_sub")
            local leaf_id="appkit.$section_slug${sub_part:+.$sub_part}.$sym_slug"
            local sym_disp=$(swift_esc "$sym_name")
            leaf_lines+=(".leaf(Leaf(id: \"$leaf_id\", displayName: \"$sym_disp\", apiSignature: \"$sym_disp\", framework: .appKit, docMarkdownPath: \"$doc_path\", availability: $([ -n "$avail" ] && echo "\"$avail\"" || echo nil), pageBuilder: .placeholder))")
        fi
    done < "$DOC_ROOT/_links/appkit-urls.md"
    flush_section

    # Section assembly
    {
        echo ""
        echo "let appKitTree: CatalogNode = .section(SectionNode("
        echo "    id: \"appkit\","
        echo "    title: \"AppKit\","
        echo "    symbolName: \"apple.terminal\","
        echo "    children: ["
        for v in "${folder_vars[@]}"; do
            echo "        $v,"
        done
        echo "    ]"
        echo "))"
    } >> "$out"

    echo "Wrote $out (${#folder_vars[@]} folders)"
}

write_swiftui
write_appkit

echo "Done."
